/** Computer & electronics manufacturers for IT asset inventory. */
export const COMPUTER_BRANDS = [
  { code: 'HP', name: 'HP' },
  { code: 'DELL', name: 'Dell' },
  { code: 'KYOCERA', name: 'Kyocera' },
  { code: 'HISENSE', name: 'Hisense' },
  { code: 'LENOVO', name: 'Lenovo' },
  { code: 'APPLE', name: 'Apple' },
  { code: 'SAMSUNG', name: 'Samsung' },
  { code: 'ASUS', name: 'Asus' },
  { code: 'ACER', name: 'Acer' },
  { code: 'CANON', name: 'Canon' },
  { code: 'EPSON', name: 'Epson' },
  { code: 'BROTHER', name: 'Brother' },
  { code: 'MICROSOFT', name: 'Microsoft' },
  { code: 'CISCO', name: 'Cisco' },
  { code: 'HUAWEI', name: 'Huawei' },
  { code: 'LG', name: 'LG' },
  { code: 'SONY', name: 'Sony' },
  { code: 'TOSHIBA', name: 'Toshiba' },
  { code: 'FUJITSU', name: 'Fujitsu' },
  { code: 'HPE', name: 'HPE' },
  { code: 'INTEL', name: 'Intel' },
  { code: 'AMD', name: 'AMD' },
  { code: 'LOGITECH', name: 'Logitech' },
  { code: 'VIEWSONIC', name: 'ViewSonic' },
  { code: 'BENQ', name: 'BenQ' },
  { code: 'PHILIPS', name: 'Philips' },
  { code: 'PANASONIC', name: 'Panasonic' },
  { code: 'RICOH', name: 'Ricoh' },
  { code: 'XEROX', name: 'Xerox' },
  { code: 'MSI', name: 'MSI' },
];
