/**
 * Goodfellow Finance Limited branches — sourced from:
 * https://goodfellow.co.zm/branches.html (28 locations, 10 provinces)
 */
export const GOODFELLOW_BRANCHES = [
  // Lusaka Province
  {
    code: 'GFL-LUS-01',
    name: 'Head Office - Rhodespark',
    city: 'Lusaka',
    address: 'Plot No. 4448/8 Chaholi Road, Rhodespark, Lusaka',
    phone: '+260 211 238 719 / +260 957 224 792',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-LUS-02',
    name: 'Cairo Road Branch',
    city: 'Lusaka',
    address: 'Woodgate House, Plot No. 2103/4/5 202, Cairo Road Next To Stanbic, Lusaka',
    phone: '+260 972 835 214',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-LUS-03',
    name: 'Lusaka Premium House',
    city: 'Lusaka',
    address: 'Plot 7431 Unit 603, Independence Avenue, Lusaka',
    phone: '+260 972 835 207',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-LUS-04',
    name: 'Lusaka UTH',
    city: 'Lusaka',
    address: 'Kovo Workshop Opp. Centre Of Excellence, Pediatrics Hospital, Lusaka',
    phone: '+260 972 835 286',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-CHG-01',
    name: 'Chongwe Branch',
    city: 'Chongwe',
    address: 'Shop No. 5, Maimba Mall, Great East Road, Main Town, Chongwe',
    phone: '+260 972 835 367',
    manager_name: '',
    status: 'active',
  },
  // Copperbelt Province
  {
    code: 'GFL-KIT-01',
    name: 'Kitwe Branch',
    city: 'Kitwe',
    address: 'Permanent House, Ground Floor, Stand No. 495/6, Kaunda Square, Kitwe',
    phone: '+260 763 882 434',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-NDL-01',
    name: 'Ndola Branch',
    city: 'Ndola',
    address: 'Watch It Grow Complex, 1st Floor Room 13, Chimwemwe Road, Ndola',
    phone: '+260 763 882 431',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-CHI-01',
    name: 'Chingola Branch',
    city: 'Chingola',
    address: 'The Park Mall, Shop No. 4, Chingola',
    phone: '+260 763 882 432',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-MUF-01',
    name: 'Mufulira Branch',
    city: 'Mufulira',
    address: 'Central Business District, Mufulira',
    phone: '',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-LUA-01',
    name: 'Luanshya Branch',
    city: 'Luanshya',
    address: 'Kafubu House, Ground Floor, Luanshya',
    phone: '+260 763 882 433',
    manager_name: '',
    status: 'active',
  },
  // Southern Province
  {
    code: 'GFL-LIV-01',
    name: 'Livingstone Branch',
    city: 'Livingstone',
    address: 'Plot No. 106, Room 203/205, Liso House, Zsic Building, Mosi-O-Tunya Road, Livingstone',
    phone: '+260 763 882 425',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-CHO-01',
    name: 'Choma Branch',
    city: 'Choma',
    address: 'Section J1 Off Plot 79A, Choma Hotel, Ground Floor, Choma',
    phone: '+260 763 882 426',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-MAZ-01',
    name: 'Mazabuka Branch',
    city: 'Mazabuka',
    address: 'Galaba House, Room G-04, Mazabuka',
    phone: '+260 762 172 370',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-MON-01',
    name: 'Monze Branch',
    city: 'Monze',
    address: 'Acropolis Enterprise Ltd, Tamorana Complex, Plot No. 670, Livingstone Road, Monze',
    phone: '+260 762 172 517',
    manager_name: '',
    status: 'active',
  },
  // Eastern Province
  {
    code: 'GFL-CHP-01',
    name: 'Chipata Branch',
    city: 'Chipata',
    address: 'Mikalile Complex, Office No. 10, Next To Shoprite, Umozhi Highway, Chipata',
    phone: '+260 763 882 428',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-PET-01',
    name: 'Petauke Branch',
    city: 'Petauke',
    address: 'Plot No. Pet/105, Next To Zanaco/Syngenta, Main Boma Road, Petauke',
    phone: '+260 763 882 427',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-LUN-01',
    name: 'Lundazi Branch',
    city: 'Lundazi',
    address: 'Plot No. 642, Town Centre, Lundazi',
    phone: '+260 763 882 429',
    manager_name: '',
    status: 'active',
  },
  // Central Province
  {
    code: 'GFL-KAB-01',
    name: 'Kabwe Branch',
    city: 'Kabwe',
    address: 'Stand 7700a, Shop No. 28, Next To Debonairs, Independence Road, Kabwe',
    phone: '+260 763 882 430',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-MUM-01',
    name: 'Mumbwa Branch',
    city: 'Mumbwa',
    address: 'Shop No. Lw 07, Dt Business Complex, Mumbwa',
    phone: '+260 763 882 405',
    manager_name: '',
    status: 'active',
  },
  // Northern Province
  {
    code: 'GFL-KAS-01',
    name: 'Kasama Branch',
    city: 'Kasama',
    address: 'Room 1 & 2, Machi Chibusa Building, Plot No. 3226, Mukulumpe Rd, Kasama',
    phone: '+260 763 882 403',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-MBA-01',
    name: 'Mbala Branch',
    city: 'Mbala',
    address: 'Old Green Shop, Makanta Road, Town Market, Mbala',
    phone: '+260 972 835 316',
    manager_name: '',
    status: 'active',
  },
  // Luapula Province
  {
    code: 'GFL-MAN-01',
    name: 'Mansa Branch',
    city: 'Mansa',
    address: 'Kabwe Bwafwano Mall, Plot No. 1971, Kawambwa Rd Opp. Provincial Admin, Mansa',
    phone: '+260 763 882 402',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-KAW-01',
    name: 'Kawambwa Branch',
    city: 'Kawambwa',
    address: 'Plot No. 2794, Shop No. 8, Old Mushota Road, Kawambwa',
    phone: '+260 954 392 821',
    manager_name: '',
    status: 'active',
  },
  // Western Province
  {
    code: 'GFL-MOG-01',
    name: 'Mongu Branch',
    city: 'Mongu',
    address: 'Barotse Mall, Shop No. 6, Mongu',
    phone: '+260 763 882 397',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-KAO-01',
    name: 'Kaoma Branch',
    city: 'Kaoma',
    address: 'Freedom Way, Next To Ngucha Filling Station, Kaoma',
    phone: '+260 763 882 407',
    manager_name: '',
    status: 'active',
  },
  // North-Western Province
  {
    code: 'GFL-SOL-01',
    name: 'Solwezi Branch',
    city: 'Solwezi',
    address: 'Chikamoneka Complex, SS Vasant Building, Plot No. 163 Room 6, Next To Solwezi Local Court, Solwezi',
    phone: '+260 763 882 398',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-KAL-01',
    name: 'Kalumbila Branch',
    city: 'Kalumbila',
    address: 'Plot # 1002, Banana 2 East, Nkisu Road, Kalumbila',
    phone: '+260 761 454 886',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-LUM-01',
    name: 'Lumwana Branch',
    city: 'Lumwana',
    address: 'Noamba Shopping Complex, Mwinilunga Road, Manyama, Lumwana',
    phone: '+260 772 490 971',
    manager_name: '',
    status: 'active',
  },
  // Muchinga Province
  {
    code: 'GFL-CHN-01',
    name: 'Chinsali Branch',
    city: 'Chinsali',
    address: 'Plot No. 525, Along Nambuluma Road, Opposite Post Office, Chinsali',
    phone: '+260 763 882 401',
    manager_name: '',
    status: 'active',
  },
  {
    code: 'GFL-NAK-01',
    name: 'Nakonde Branch',
    city: 'Nakonde',
    address: 'Shop No. 1 Wamukopeka Building, Nakonde',
    phone: '+260 762 172 511',
    manager_name: '',
    status: 'active',
  },
];
