export const EXTERNAL_API_PAGINATION = {
  title: 'Pagination',
  description: 'List endpoints return paginated JSON. Use limit (max 200) and offset, or page with limit.',
  params: [
    { name: 'limit', type: 'integer', default: '50', description: 'Number of records per page (max 200).' },
    { name: 'offset', type: 'integer', default: '0', description: 'Number of records to skip.' },
    { name: 'page', type: 'integer', default: '1', description: 'Alternative to offset — page number when using limit.' },
    { name: 'search', type: 'string', default: '—', description: 'Free-text search across relevant fields.' },
  ],
  responseShape: {
    ok: true,
    data: ['…records…'],
    pagination: {
      total: 120,
      limit: 50,
      offset: 0,
      page: 1,
      pages: 3,
    },
  },
};

export const EXTERNAL_API_ERRORS = [
  { status: 401, meaning: 'Missing, invalid, or expired API key.' },
  { status: 403, meaning: 'IP not whitelisted for the key, or missing required scope.' },
  { status: 404, meaning: 'Resource not found.' },
  { status: 429, meaning: 'Rate limit exceeded (120 requests/minute per key).' },
  { status: 500, meaning: 'Server error.' },
];

export const EXTERNAL_API_ENDPOINT_DOCS = [
  {
    id: 'health',
    method: 'GET',
    path: '/health',
    scope: 'Public',
    summary: 'Health check — no API key required.',
    queryParams: [],
    responseExample: {
      ok: true,
      service: 'gfl-external-api',
      version: 'v1',
    },
  },
  {
    id: 'assets-list',
    method: 'GET',
    path: '/assets',
    scope: 'assets.read',
    summary: 'List inventory assets with branch and assigned employee.',
    queryParams: [
      { name: 'limit', type: 'integer', description: 'Page size (max 200).' },
      { name: 'offset', type: 'integer', description: 'Pagination offset.' },
      { name: 'search', type: 'string', description: 'Search S/N, name, category, branch, or employee.' },
      { name: 'branchId', type: 'string', description: 'Filter by branch ID.' },
      { name: 'employeeId', type: 'string', description: 'Filter by assigned employee ID.' },
      { name: 'status', type: 'string', description: 'Filter by product status.' },
    ],
    responseExample: {
      ok: true,
      data: [
        {
          id: 'prod-abc123',
          serialNumber: 'SN-001234',
          name: 'Dell Latitude 5540',
          category: 'Laptop',
          brand: { id: 'br-1', code: 'DELL', name: 'Dell' },
          status: 'active',
          quantity: 1,
          branch: { id: 'br-lusaka', code: 'LUN', name: 'Lusaka HQ' },
          employee: { id: 'emp-1', employeeCode: 'EMP-001', fullName: 'Jane Banda' },
          updatedAt: '2026-07-18T10:30:00.000Z',
        },
      ],
      pagination: { total: 1, limit: 50, offset: 0, page: 1, pages: 1 },
    },
  },
  {
    id: 'assets-get',
    method: 'GET',
    path: '/assets/:id',
    scope: 'assets.read',
    summary: 'Get a single asset by ID.',
    queryParams: [],
    responseExample: {
      ok: true,
      data: {
        id: 'prod-abc123',
        serialNumber: 'SN-001234',
        name: 'Dell Latitude 5540',
        category: 'Laptop',
        employee: { id: 'emp-1', employeeCode: 'EMP-001', fullName: 'Jane Banda' },
        updatedAt: '2026-07-18T10:30:00.000Z',
      },
    },
  },
  {
    id: 'employees-list',
    method: 'GET',
    path: '/employees',
    scope: 'employees.read',
    summary: 'List employees with branch and asset count.',
    queryParams: [
      { name: 'limit', type: 'integer', description: 'Page size (max 200).' },
      { name: 'offset', type: 'integer', description: 'Pagination offset.' },
      { name: 'search', type: 'string', description: 'Search code, name, email, phone, job title, or branch.' },
      { name: 'branchId', type: 'string', description: 'Filter by branch ID.' },
      { name: 'status', type: 'string', description: 'Filter by employee status.' },
    ],
    responseExample: {
      ok: true,
      data: [
        {
          id: 'emp-1',
          employeeCode: 'EMP-001',
          firstName: 'Jane',
          lastName: 'Banda',
          fullName: 'Jane Banda',
          email: 'jane.banda@goodfellow.co.zm',
          phone: '+260971234567',
          jobTitle: 'Branch Manager',
          status: 'active',
          branch: { id: 'br-lusaka', code: 'LUN', name: 'Lusaka HQ' },
          assetCount: 3,
          updatedAt: '2026-07-18T09:00:00.000Z',
        },
      ],
      pagination: { total: 1, limit: 50, offset: 0, page: 1, pages: 1 },
    },
  },
  {
    id: 'employees-get',
    method: 'GET',
    path: '/employees/:id',
    scope: 'employees.read',
    summary: 'Get a single employee by ID.',
    queryParams: [],
    responseExample: {
      ok: true,
      data: {
        id: 'emp-1',
        employeeCode: 'EMP-001',
        fullName: 'Jane Banda',
        assetCount: 3,
        branch: { id: 'br-lusaka', code: 'LUN', name: 'Lusaka HQ' },
      },
    },
  },
  {
    id: 'employees-assets',
    method: 'GET',
    path: '/employees/:id/assets',
    scope: 'employees.read',
    summary: 'List all assets assigned to one employee.',
    queryParams: [
      { name: 'limit', type: 'integer', description: 'Page size (max 200).' },
      { name: 'offset', type: 'integer', description: 'Pagination offset.' },
      { name: 'search', type: 'string', description: 'Search S/N, name, or category.' },
    ],
    responseExample: {
      ok: true,
      data: [{ id: 'prod-abc123', serialNumber: 'SN-001234', name: 'Dell Latitude 5540' }],
      pagination: { total: 1, limit: 50, offset: 0, page: 1, pages: 1 },
    },
  },
  {
    id: 'assignments-list',
    method: 'GET',
    path: '/assignments',
    scope: 'assignments.read',
    summary: 'Flat list of asset-to-employee assignment links.',
    queryParams: [
      { name: 'limit', type: 'integer', description: 'Page size (max 200).' },
      { name: 'offset', type: 'integer', description: 'Pagination offset.' },
      { name: 'search', type: 'string', description: 'Search asset S/N, name, or employee details.' },
      { name: 'branchId', type: 'string', description: 'Filter by branch ID.' },
      { name: 'employeeId', type: 'string', description: 'Filter by employee ID.' },
    ],
    responseExample: {
      ok: true,
      data: [
        {
          assetId: 'prod-abc123',
          serialNumber: 'SN-001234',
          assetName: 'Dell Latitude 5540',
          category: 'Laptop',
          employeeId: 'emp-1',
          employeeCode: 'EMP-001',
          employeeName: 'Jane Banda',
          branchCode: 'LUN',
          branchName: 'Lusaka HQ',
          updatedAt: '2026-07-18T10:30:00.000Z',
        },
      ],
      pagination: { total: 1, limit: 50, offset: 0, page: 1, pages: 1 },
    },
  },
];
